### ISSUE TITLE
add baseAvatarUrl field to the UserSchema.

### ISSUE THREAD

**Issue by AdrianValdes** [angetaute-fischtstaebchen/records-server#12]
The UserSchema has the code 
```
baseAvatarUrl: {
      type: String,
      required: true,
      default: 'http://localhost:5000/statics/avatar',
    },
```
But the field baseAvatarUrl is not being created in the seed

**Comment by AdrianValdes** [comment]
hi @chmette ,

Could you check why is this not working? Is the code in the seed supposed to create the user also with the default values? Yes, right?

**Comment by chmette** [comment]
yes, i can check sure, but I ll first like to check on github states. I dont know what to do with my last state in the branch you commited and merged in the file. please ets solve that , and then i check the other thing. default for avatar was :
`'http://localhost:5000/statics/avatar/01.png'`  

base avatar is new, i d like to check out when everything is up to date

**Comment by chmette** [comment]
Good morning @AdrianValdes 
i checked it. both avatar and avatarBaseUrl are  created with default data , we do not need to create them in the seed directly.
It worked.  I also cleaned the data base a bit.
